install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

test_script:
  - cargo build
 # see https://github.com/steveklabnik/rustdoc/issues/22
 #- cargo test
 
# https://twitter.com/RustStatus/status/887694846890307584
# https://twitter.com/RustStatus/status/887703618115297280
environment:
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false
