language: rust

rust:
  # someday, but rls relies on nightly right now.
  # - stable
  # - beta
  - nightly

cache:
  - cargo

before_install:
  - nvm install 8.1.4
  - ./ci-scripts/rustfmt.sh

script:
  - rustfmt --write-mode diff build.rs
  - rustfmt --write-mode diff $(find src -type f | grep .rs)
  - cd frontend && npm install && ember build -prod && npm run test
  - cd .. && cargo build && cargo test && cd example
  - ../target/debug/rustdoc build
